name: test

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Go coverage
        uses: gwatts/go-coverage-action@v2
        with:
          cover-mode: atomic
          cover-pkg: ./...
          test-pkgs: ./...
